# CAUTION: This downloads about 6.5 GB of Code
#Source: https://medium.com/issuehunt/50-top-java-projects-on-github-adbfe9f67dbc

git clone https://github.com/ReactiveX/RxJava.git
git clone https://github.com/elastic/elasticsearch
git clone https://github.com/square/retrofit
git clone https://github.com/spring-projects/spring-boot
git clone https://github.com/google/guava
git clone https://github.com/PhilJay/MPAndroidChart
git clone https://github.com/bumptech/glide
git clone https://github.com/spring-projects/spring-framework
git clone https://github.com/JakeWharton/butterknife
git clone https://github.com/airbnb/lottie-android
git clone https://github.com/apache/incubator-dubbo
git clone https://github.com/zxing/zxing
git clone https://github.com/greenrobot/EventBus
git clone https://github.com/Blankj/AndroidUtilCode
git clone https://github.com/nostra13/Android-Universal-Image-Loader
git clone https://github.com/square/picasso
git clone https://github.com/skylot/jadx
git clone https://github.com/facebook/fresco
git clone https://github.com/netty/netty
git clone https://github.com/libgdx/libgdx
git clone https://github.com/Netflix/Hystrix
git clone https://github.com/alibaba/fastjson
git clone https://github.com/CymChad/BaseRecyclerViewAdapterHelper
git clone https://github.com/afollestad/material-dialogs
git clone https://github.com/chrisbanes/PhotoView
git clone https://github.com/Tencent/tinker
git clone https://github.com/lgvalle/Material-Animations
git clone https://github.com/nickbutcher/plaid
git clone https://github.com/jfeinstein10/SlidingMenu
git clone https://github.com/jenkinsci/jenkins
git clone https://github.com/google/ExoPlayer
git clone https://github.com/greenrobot/greenDAO
git clone https://github.com/realm/realm-java
git clone https://github.com/orhanobut/logger
git clone https://github.com/bazelbuild/bazel
git clone https://github.com/mybatis/mybatis-3
git clone https://github.com/square/dagger
git clone https://github.com/google/guice
git clone https://github.com/google/auto
git clone https://github.com/junit-team/junit4
git clone https://github.com/mockito/mockito
git clone https://github.com/square/javapoet
git clone https://github.com/OpenRefine/OpenRefine
git clone https://github.com/google/j2objc
git clone https://github.com/facebook/rebound
git clone https://github.com/scribejava/scribejava
git clone https://github.com/square/moshi
git clone https://github.com/socketio/socket.io-client-java
